import type { Frame } from '../types';
export function rnd(n: number, lo: number, hi: number): number[];
export function mkEls(vals: number[]): { id: string; v: number }[];
export function snapArr(...args: never[]): Frame;
export function keepDone(roles: Record<string, string>): void;
export function snapLin(...args: never[]): Frame;
export function snapTree(...args: never[]): Frame;
export function snapGraph(...args: never[]): Frame;
export function buildTree(vals: number[]): { root: TreeNode; nodes: Record<string, TreeNode> };
export interface TreeNode { id: string; v: number; left: TreeNode | null; right: TreeNode | null; parent: string | null; x: number; y: number }
export function traversal(mode: 'pre' | 'in' | 'post'): Frame[];
export function bubble(vals: number[]): Frame[];
export function selection(vals: number[]): Frame[];
export function insertion(vals: number[]): Frame[];
export function quick(vals: number[]): Frame[];
export function merge(vals: number[]): Frame[];
export function linearSearch(vals: number[]): Frame[];
export function binarySearch(vals: number[]): Frame[];
export function stackDemo(): Frame[];
export function queueDemo(): Frame[];
export function hashDemo(): Frame[];
export function bstInsert(): Frame[];
export function bfs(): Frame[];
export function dfs(): Frame[];
export function dijkstra(): Frame[];
export function nbrs(u: string): [string, number][];
export const GNODES: Record<string, [number, number]>;
export const GEDGES: [string, string, number][];
export const TREE_VALUES: number[];
