// @ts-nocheck
const DRILLS=[
 {q:'You store 50 million session tokens. You need to check "is this token valid" on every request, and expire old ones.',
  o:['A sorted array with binary search','A hash set, with expiry handled separately','A linked list'],a:1,
  why:'Membership checks are the hot path and you never need the tokens in order, so hashing wins. Expiry is a separate concern, usually a time-to-live in the store itself rather than something your data structure handles.'},
 {q:'A leaderboard needs "top 10" and "what rank is player X" on every page load, with scores updating constantly.',
  o:['A hash map from player to score','An ordered structure keyed by score, such as a sorted set','Re-sort an array after every score change'],a:1,
  why:'A hash map cannot answer ranking questions without scanning everyone. Re-sorting on every update is O(n log n) per change. An ordered structure gives you top-k and rank directly, which is exactly why Redis ships a sorted set type.'},
 {q:'A 2 GB CSV must be sorted by timestamp on a laptop with 16 GB of RAM.',
  o:['Load it and call the library sort','Write an external merge sort','Insert every row into a database first'],a:0,
  why:'It fits in memory with room to spare, so the boring answer is correct. External sorting is for data that genuinely does not fit. Reaching for the sophisticated tool when the simple one works is its own kind of mistake.'},
 {q:'Same file, but it is now 200 GB and the machine still has 16 GB.',
  o:['Load it and call the library sort','Sort chunks to disk and merge them, or use a tool that already does','Use a faster comparison function'],a:1,
  why:'Nothing about your comparison function matters if the data cannot be loaded. This is the external sort case, and command-line sort already implements it, so you probably do not write it yourself.'},
 {q:'Your API is slow. Profiling shows one endpoint calls list.contains(id) inside a loop over another list.',
  o:['Add a cache in front of the endpoint','Convert the inner list to a set before the loop','Add more server instances'],a:1,
  why:'That pattern is O(n × m). Building a set once makes it O(n + m), often a hundredfold improvement for three lines of change. Caching or scaling hides the problem and keeps paying for it.'},
 {q:'You need the median response time from 10 million recorded latencies, once per minute.',
  o:['Sort all 10 million and take the middle','Quickselect, or a percentile estimator such as t-digest','Keep a running average'],a:1,
  why:'An average is not a median and hides the tail entirely. Full sorting does far more work than the question requires. Selection gets the exact answer in linear time, and streaming estimators get a close answer in constant memory.'},
 {q:'An autocomplete box must suggest all products starting with the typed prefix.',
  o:['A hash map keyed by product name','A sorted structure, where a prefix is a contiguous range','Scan all products on each keystroke'],a:1,
  why:'Hashing destroys the relationship between similar keys, so a hash map cannot find "everything starting with cam". In sorted order those entries sit together, so the query becomes a range walk. A trie is the specialised version of the same idea.'},
 {q:'A job scheduler must always run the highest-priority waiting job next.',
  o:['A queue','A priority queue, that is, a heap','A sorted list, re-sorted on every insert'],a:1,
  why:'A plain queue gives you arrival order, not priority. Re-sorting on every insert is O(n log n) per job. A heap gives you insert and extract-highest in O(log n), which is what every scheduler and every Dijkstra implementation uses.'},
 {q:'You are deduplicating 100 million log lines and cannot fit them all in memory.',
  o:['A hash set of every line','Sort the file, then drop adjacent duplicates','Compare every line to every other line'],a:1,
  why:'Once sorted, duplicates are neighbours, so one pass removes them and sorting can spill to disk. A hash set of everything is the in-memory answer and here it does not fit. A Bloom filter is the third option when an approximate answer is acceptable.'},
 {q:'Your recursive directory walker crashes with a stack overflow on a customer machine.',
  o:['Increase the recursion limit','Rewrite it with an explicit stack','Catch the exception and continue'],a:1,
  why:'Raising the limit moves the failure rather than removing it, and the next customer has a deeper tree. An explicit stack uses the heap, which is far larger, and makes the depth a visible variable you can bound.'},
 {q:'Two services each hold a lock the other is waiting for. Nothing progresses.',
  o:['A deadlock, which is a cycle in the wait-for graph','A race condition','A memory leak'],a:0,
  why:'Detection is cycle detection over a graph of who waits for whom, which is the DFS check you have already seen. Prevention is usually a fixed lock ordering, which makes a cycle impossible by construction.'},
 {q:'A social feature needs "people within two connections of you" for a user with 900 friends.',
  o:['BFS to depth 2','DFS across the whole graph',"Dijkstra's algorithm"],a:0,
  why:'BFS levels are degrees of separation, so you simply stop after level two. DFS would wander far away before finishing anything nearby, and Dijkstra solves weighted costs, which is a question nobody asked here.'},
 {q:'A delivery route must minimise fuel cost, where each road segment has a different cost.',
  o:['BFS, because it finds the shortest path',"Dijkstra, or A* if you have a distance estimate",'Sort the roads by cost and take the cheapest ones'],a:1,
  why:'BFS minimises the number of segments, which is not the same as minimising cost. Weighted edges are precisely the case Dijkstra exists for. Greedily grabbing cheap roads gives you a minimum spanning tree, which answers a different question.'},
 {q:'A configuration object is used as a key in a hash map, then one of its fields is changed.',
  o:['Nothing, hash maps handle this','The entry becomes unreachable because the key now hashes elsewhere','The map re-sorts itself'],a:1,
  why:'The entry still occupies its original bucket, but lookups now compute a different bucket and find nothing. The map reports the key as absent while still holding it. Use immutable keys; several languages enforce this and the ones that do not make this bug easy to write.'},
 {q:'A queue between your producer and consumer has been growing steadily for an hour.',
  o:['Increase the queue size','Add consumers, or reduce the work each message needs','Restart the producer'],a:1,
  why:'A growing queue means arrival rate exceeds service rate. A bigger buffer only delays the failure while making the eventual latency worse. Either serve faster or accept less, and the queue depth graph is your earliest warning of both.'},
 {q:'A query filtering on status and ordering by created_at is slow on a 20 million row table.',
  o:['Add an index covering the filter and the sort order','Add more memory to the database','Split the query in two'],a:0,
  why:'Without a matching index the engine scans every row and then sorts the survivors, sometimes spilling to disk. An index that matches both the filter and the ordering removes the scan and the sort together, which is usually the difference between seconds and milliseconds.'},
 {q:'You must keep a rolling list of the 100 most recent events in memory, cheaply.',
  o:['A list you truncate after every append','A fixed-size ring buffer, or a deque with a max length','A sorted set by timestamp'],a:1,
  why:'Truncating copies the list every time. A ring buffer or bounded deque makes both the append and the eviction O(1) with no allocation, which is why logging and metrics libraries use them.'},
 {q:'An interviewer asks you to find whether any two numbers in a list sum to a target.',
  o:['Check every pair','Put each number in a hash set and look for target minus current','Sort the list first, always'],a:1,
  why:'Checking every pair is O(n²). One pass with a hash set is O(n) and is the answer they are listening for. Sorting with two pointers is also valid at O(n log n), and is the better answer if you are told you cannot use extra memory.'}
];

export { DRILLS };
