// @ts-nocheck
import { EXTRA_STDLIB } from './extra.js';
const SORT_CALLS=[
  ['Python','sorted(xs)  |  xs.sort()','Timsort. Stable. Give it key=lambda r: r.age to sort objects.'],
  ['Java','Collections.sort(list)  |  Arrays.sort(arr)','Timsort for objects, dual-pivot quicksort for primitives.'],
  ['JavaScript','arr.sort((a, b) => a - b)','Without the comparator it sorts as text, so 10 comes before 9.'],
  ['C++','std::sort(v.begin(), v.end())','Introsort. Use std::stable_sort when ties must keep their order.']];

const STDLIB={
  bubble:{calls:SORT_CALLS,costs:[['Library sort','O(n log n)'],['Your bubble sort','O(n²)']],
    gotcha:'There is no situation in ordinary application code where hand-written bubble sort is the right call.'},
  selection:{calls:SORT_CALLS,costs:[['Library sort','O(n log n)'],['Your selection sort','O(n²)']],
    gotcha:'If you truly need to minimise writes, say so in a comment, because the next reader will assume this is a mistake.'},
  insertion:{calls:SORT_CALLS,costs:[['Library sort','O(n log n)'],['Insertion on nearly sorted data','close to O(n)']],
    gotcha:'Library sorts already detect nearly-sorted input. Timsort finds existing sorted runs and reuses them, so you rarely beat it by hand.'},
  merge:{calls:SORT_CALLS,costs:[['Library sort','O(n log n)'],['Merging k sorted sources','O(n log k) with a heap']],
    gotcha:'To merge many sorted streams use a heap: Python heapq.merge, Java PriorityQueue, C++ std::priority_queue.'},
  quick:{calls:SORT_CALLS.concat([['Python','statistics.median(xs)','For a median specifically, do not sort by hand.']]),
    costs:[['Library sort','O(n log n)'],['Select k-th (quickselect)','O(n) average']],
    gotcha:'C++ has std::nth_element for exactly the quickselect job. Most other languages make you sort, which is fine below a few hundred thousand items.'},
  linear:{calls:[['Python','x in xs  |  next(r for r in xs if r.id == k)','in on a list is a scan; in on a set is a hash lookup.'],
      ['Java','list.contains(x)','O(n) on ArrayList, O(1) on HashSet.'],
      ['JavaScript','arr.includes(x)  |  arr.find(fn)','Both scan. A Set or Map does not.'],
      ['C++','std::find(v.begin(), v.end(), x)','Returns an iterator, compare it against v.end().']],
    costs:[['Scan a list','O(n)'],['Hash set lookup','O(1)']],
    gotcha:'A scan inside a loop over the same data is the most common accidental O(n²) in real code. If you see in or contains inside a loop, reach for a set.'},
  binary:{calls:[['Python','bisect.bisect_left(xs, x)  |  bisect.insort(xs, x)','Standard library, already correct. Do not hand-roll it.'],
      ['Java','Collections.binarySearch(list, key)','Negative return encodes the insertion point.'],
      ['JavaScript','—','No built-in. This is one of the few you may legitimately write yourself.'],
      ['C++','std::lower_bound(v.begin(), v.end(), x)','Returns the first element not less than x.']],
    costs:[['Binary search','O(log n)'],['Keeping a list sorted on insert','O(n) per insert']],
    gotcha:'bisect_left and lower_bound give you the insertion point, which is more useful than a plain found or not found. Use them for range boundaries.'},
  stack:{calls:[['Python','xs.append(x)  |  xs.pop()','A plain list is already a perfectly good stack.'],
      ['Java','Deque<T> s = new ArrayDeque<>(); s.push(x); s.pop();','Do not use the legacy Stack class, it is synchronised and slow.'],
      ['JavaScript','arr.push(x)  |  arr.pop()','Both O(1).'],
      ['C++','std::stack<T>','Wraps a deque.']],
    costs:[['push / pop / peek','O(1)']],
    gotcha:'Recursion is a stack you did not declare. If depth might reach the tens of thousands, convert it to an explicit stack before it crashes in production.'},
  queue:{calls:[['Python','from collections import deque; q.append(x); q.popleft()','Never use list.pop(0).'],
      ['Java','Deque<T> q = new ArrayDeque<>(); q.add(x); q.poll();','Use LinkedBlockingQueue across threads.'],
      ['JavaScript','—','arr.shift() is O(n). For big queues keep a head index or use a library deque.'],
      ['C++','std::queue<T>','Wraps a deque.']],
    costs:[['deque append / popleft','O(1)'],['list.pop(0) or arr.shift()','O(n)']],
    gotcha:'This is the single most common silent performance bug for beginners. Popping the front of an array shifts every remaining element.'},
  hashmap:{calls:[['Python','d = {}  |  s = set()  |  collections.Counter(xs)','Counter is a hash map built for tallying.'],
      ['Java','new HashMap<>()  |  new HashSet<>()','Override equals and hashCode together on key classes or lookups silently fail.'],
      ['JavaScript','new Map()  |  new Set()','Prefer Map over a plain object for non-string keys and for size.'],
      ['C++','std::unordered_map  |  std::unordered_set','std::map is the ordered tree, not the hash map. Easy to pick the wrong one.']],
    costs:[['get / put / contains','O(1) average'],['Iteration order','not sorted, and not guaranteed stable']],
    gotcha:'A mutable object used as a key is a trap. Change a field after inserting and the entry becomes unreachable, because it now hashes to a different bucket.'},
  'bst-insert':{calls:[['Python','sortedcontainers.SortedDict (third party)','Python has no ordered map in the standard library, which surprises people.'],
      ['Java','new TreeMap<>()  |  new TreeSet<>()','Red-black tree. Gives firstKey, headMap, tailMap, subMap.'],
      ['JavaScript','—','No ordered map. Sort keys, or use a library.'],
      ['C++','std::map  |  std::set','Red-black tree, sorted iteration, lower_bound built in.']],
    costs:[['get / put','O(log n)'],['Range query','O(log n + k) for k results'],['Sorted iteration','O(n), no sorting needed']],
    gotcha:'Reach for a tree map only when you need order. For plain lookups a hash map is faster and simpler, and choosing the tree by default costs you performance for nothing.'},
  'tree-pre':{calls:[['Any language','recursion, or an explicit stack','Push the node, then push its children in reverse so the left child comes off first.']],
    costs:[['Full traversal','O(n)'],['Extra space','O(h), the height of the tree']],
    gotcha:'On an unbalanced tree the height can be n, so recursive traversal on user-supplied data is a stack overflow waiting to happen.'},
  'tree-in':{calls:[['Java','treeMap.entrySet()  |  treeMap.subMap(lo, hi)','Iteration is an in-order walk, which is why it comes out sorted.'],
      ['C++','for (auto& kv : map)  |  map.lower_bound(k)','Same guarantee.'],
      ['SQL','ORDER BY col, with an index on col','The database walks the index instead of sorting.']],
    costs:[['Full traversal','O(n)'],['Range walk','O(log n + k)']],
    gotcha:'If your ORDER BY matches an existing index, the sort disappears from the query plan. If it does not, the database sorts every matching row, sometimes on disk.'},
  'tree-post':{calls:[['Any language','recursion, children before the node','Or two stacks, if you must do it iteratively.']],
    costs:[['Full traversal','O(n)'],['Extra space','O(h)']],
    gotcha:'Any bottom-up aggregate is post-order: folder sizes, rolled-up totals, dependency cost estimates. If a parent value depends on child values, this is your order.'},
  bfs:{calls:[['Python','from collections import deque; q = deque([start])','Plus a set for seen.'],
      ['Java','ArrayDeque for the queue, HashSet for seen',''],
      ['Libraries','networkx.shortest_path (Python), JGraphT (Java)','Use a graph library before writing your own for anything non-trivial.']],
    costs:[['BFS','O(V + E)'],['Space','O(V) for the queue and seen set']],
    gotcha:'Mark nodes seen when you enqueue them, not when you dequeue them. Marking on dequeue lets the same node enter the queue several times and quietly doubles the work.'},
  dfs:{calls:[['Python','recursion, or an explicit list as a stack','sys.setrecursionlimit is a warning sign, not a fix.'],
      ['Libraries','networkx.topological_sort, networkx.simple_cycles','Cycle detection and topological sort are already written.']],
    costs:[['DFS','O(V + E)'],['Recursion depth','up to O(V)']],
    gotcha:'Python defaults to about 1000 recursion frames. A graph deeper than that crashes, and graphs built from user data get deep in ways you did not plan for.'},
  dijkstra:{calls:[['Python','heapq for the priority queue, or networkx.dijkstra_path','heapq is a min-heap of tuples: (distance, node).'],
      ['Java','PriorityQueue with a comparator on distance',''],
      ['C++','std::priority_queue, with negated costs for a min-heap','Or use greater<> as the comparator.']],
    costs:[['With a heap','O(E log V)'],['Scanning for the minimum instead','O(V²)']],
    gotcha:'The version shown here scans for the cheapest node, which is O(V²). Real implementations use a priority queue. On a sparse graph that is the difference between usable and not.'}
};

Object.assign(STDLIB, EXTRA_STDLIB);

export { STDLIB, SORT_CALLS };
