// @ts-nocheck
const USE_DETAIL = {
bubble:[
`Two loops, one inside the other, where the inner one runs afresh for every turn of the outer one. That is the whole shape interviewers are looking for. On a list of 10 items it is about 100 steps; on 1,000 items it is about a million; on 10,000 it is a hundred million. The list grew 1,000 times but the work grew a million times. Bubble sort is the smallest piece of code that shows this, so it becomes the example everyone learns first. The real skill being tested is not sorting. It is looking at unfamiliar code and noticing that a loop inside a loop means the cost multiplies.`,
`A microcontroller is the tiny computer inside a thermostat, a washing machine or a fitness band. It might have two kilobytes of memory in total, which is smaller than this paragraph repeated a few times. Suppose it reads ten temperature readings and wants the middle one. A clever sort would need a second array to copy into, or recursion that eats stack space. Bubble sort needs one temporary variable and nothing else. At ten items, the slow algorithm still finishes in microseconds, so the thing you normally optimise for simply does not matter here. Memory does.`,
`Add a boolean variable, set it to false at the start of every pass and flip it to true whenever a swap happens. If a pass finishes without a single swap, the data was already in order and you stop immediately. That turns the algorithm into a cheap answer to a useful question: is this data already sorted? It costs one walk through the list. This matters when you receive data that is usually already in order, such as records exported from a system that sorted them, and you want to skip the sorting work rather than redo it blindly.`],

selection:[
`Flash memory and EEPROM are the chips that keep data when the power is off, in USB drives, phones and embedded devices. They physically wear out. Each storage cell survives a limited number of rewrites, often somewhere around one hundred thousand, and then it stops holding data reliably. So on these devices the question is not how many comparisons you do, since reading is cheap and harmless. It is how many times you write. Selection sort writes each position at most once, which is the fewest of any of the simple sorts, so it stretches the life of the chip.`,
`Firmware is the code burned into a device, and it often runs with hard rules: no allocating memory while running, no recursion, and every operation must finish inside a fixed time slot so the device stays responsive. Selection sort fits all of that. It is two loops and one temporary variable, it never allocates anything, and it takes exactly the same time on every input, so you can promise that it finishes within the slot. An algorithm that is usually faster but occasionally much slower is worse here, because the occasional case is the one that breaks the device.`,
`When you measure whether a change made your code faster, you need something to compare against that does not move. Most sorts speed up dramatically on data that happens to be nearly ordered, which makes benchmark numbers confusing: did your change help, or did you just feed it friendlier data? Selection sort does the identical amount of work no matter what you give it. Running it alongside gives you a fixed reference line, so you can tell the difference between a real improvement and a lucky input.`],

insertion:[
`When you call sorted() in Python or Arrays.sort() in Java, you are not getting one algorithm. You are getting a hybrid that switches strategy depending on the size of the piece it is working on. It breaks the data into small chunks, sorts each chunk with insertion sort, and then merges the sorted chunks together. Why insertion sort for the chunks? Because on 32 items the fancy algorithms spend more time on their own bookkeeping, recursion and index arithmetic than they save. The simple algorithm has almost no overhead and wins outright at that size. So this runs millions of times a day inside code you did not write.`,
`Imagine a live leaderboard during a tournament. Scores arrive one at a time. You could re-sort the whole list every time a score comes in, but that throws away the fact that the list was already sorted a second ago. Everything is in place except the one new value. Insertion sort walks that single value to its correct slot and stops. This property has a name: it is an online algorithm, meaning it can absorb new data without redoing finished work. Sort once, then maintain, rather than sort again and again.`,
`Servers write events with timestamps and send them to a central place for analysis. Network delays mean an event stamped 10:00:05 sometimes arrives after one stamped 10:00:07. The result is a list that is about 99 percent in order, with occasional items sitting one or two positions from where they belong. Insertion sort handles this in close to a single pass, because its inner loop stops the moment it finds a smaller value. A general-purpose sort would do its full amount of work without noticing that the data was nearly correct already.`],

merge:[
`You have a 50 GB log file and a machine with 8 GB of memory. You cannot load the file, so no in-memory sort can touch it. Instead you read the first 8 GB, sort that in memory, and write it back to disk as chunk one. Repeat until you have around seven sorted chunks. Now open all seven at once, look at the first line of each, write out whichever is smallest, and advance only that chunk. You repeat until every chunk is empty. At no point do you hold more than seven lines in memory. This is called external sorting, and it is how the Unix sort command handles files larger than the machine it runs on.`,
`You have 10 million orders and 2 million customers, and you need to attach each order to its customer. The obvious approach looks up each order's customer one at a time, which is 10 million separate lookups. The alternative is to sort both sides by customer id once, and then walk the two sorted lists side by side like closing a zip: advance whichever side is behind, and matches fall out naturally. You pay for two sorts and then read each list exactly once. Database engines choose between these two strategies, and the query plan shows which one it picked.`,
`A stable sort is one where two records that tie on the sort key keep the order they already had. Picture a table of tasks on screen. A user sorts by assignee, then clicks the due date column. With a stable sort, tasks sharing the same due date remain grouped by assignee underneath, which is exactly what the user expects because they built that view in two deliberate steps. With an unstable sort, the earlier arrangement is scrambled and the user assumes the table is broken. Python and Java guarantee stability precisely because people rely on this.`],

quick:[
`The sort function in the C++ standard library is not literally quick sort. It starts as quick sort. If the pivot choices go badly and the recursion gets too deep, it detects that and switches to heap sort, which is slower on average but has no bad case, so it cannot degrade to n squared. And once a piece shrinks below roughly sixteen items, it hands off to insertion sort, which beats everything at that size. Three algorithms inside one function call. The pattern is worth learning on its own: fast in the common case, with a guaranteed fallback for the rare bad case.`,
`Your service handled a million requests today and you want the 99th percentile latency, meaning the value that 99 percent of requests came in under. Sorting all million just to read one position is wasted work. Instead run the partition step once: the pivot lands in its final position, say at index 400,000, with smaller values left and larger right. You want position 990,000, which is in the right group, so you discard the entire left half and repeat on the right. Each round throws away a large chunk. You get the exact answer without ever fully sorting. This is quickselect, and it is how percentile metrics get computed cheaply.`,
`The processor does not fetch one number from memory at a time. It fetches a whole block of nearby memory into a small fast store called the cache, betting that you will want the neighbours next. If your next number is in that block, access is nearly free. If it is far away, the processor stalls and waits. Quick sort moves data within a single array using two positions that sweep toward each other, so the values it needs next are usually already in cache. Merge sort copies back and forth between two arrays. Same big-O notation, but two or three times the real running time.`],

linear:[
`A users table has 5 million rows and you run a query filtering on email. If nobody created an index on the email column, the database has no shortcut. It opens row one, compares, opens row two, compares, all the way to row 5 million. That is precisely the loop in the visualization, just with disk reads instead of array positions, and it takes seconds instead of microseconds. When you ask a database to explain a slow query and the plan says sequential scan or full table scan, this is what it is telling you. Creating an index gives it a sorted structure to jump around in instead.`,
`Building a hash map is not free. You allocate memory for the buckets, and you run the hash function over every key you insert. With ten items, that setup work costs more than simply checking all ten one by one. This is not a theoretical point: several standard libraries ship small-map implementations that store a plain list and scan it, and only convert to a real hash map once the map grows past a threshold. The lesson is that big-O describes what happens as data grows, and says nothing about which option wins when the data is tiny.`,
`When you run grep over a log file, it has no idea where the word you want appears, so it reads every line and checks each one. Double the file size and you double the time, exactly and predictably. There is no clever trick available because the file has no structure to exploit. The only escape is to build a structure in advance, which is what search systems such as Elasticsearch do: they read the text once, build an index of which words appear where, and afterwards answer queries by lookup instead of by scanning.`],

binary:[
`A database index is a structure that keeps keys in sorted order. Finding a row happens in two stages. First the database narrows down to one page, which is a fixed-size block of maybe eight kilobytes holding a few hundred sorted keys. Then, inside that page, it runs a binary search to find the exact key: check the middle, discard half, repeat. Around eight or nine comparisons inside the page and it is done. So when someone says adding an index made a query fast, the concrete meaning is that scanning was replaced by halving.`,
`A bug appeared somewhere in the last thousand commits and nobody knows which one caused it. git bisect checks out the commit halfway through the range. You build it, test it, and tell git good or bad. If it is bad, every commit after it is irrelevant and the culprit is in the earlier half. Git then jumps to the middle of that half. Around ten tests instead of a thousand. You are the comparison step, and git is running the algorithm around you. The catch is the same as always: it only works because commit history is in order.`,
`How many worker servers do you need to keep response time under 200 milliseconds at peak load? You cannot calculate it, but you can test any specific number by running a load test, which takes twenty minutes. Try 50, it is too slow. Try 100, it passes but might be more than needed. Try 75. Each test halves the range of plausible answers, so about seven tests gets you the number instead of fifty. The sorted list here is the range of candidate answers, and the comparison is the load test itself. This trick is called binary searching on the answer and it shows up in capacity planning constantly.`],

stack:[
`When main calls loadUser, which calls fetchRow, each call is placed on a pile along with its local variables and the place to return to. When fetchRow finishes, its entry is removed and control returns to loadUser exactly where it left off. This pile is the call stack, and it is why a crash report lists functions in reverse order: it is printing the pile from the top down. Reading it from the bottom up tells you the exact chain of calls that led to the failure, which is usually more useful than the error message itself.`,
`Every edit you make in an editor is pushed onto a pile. Press undo and the most recent edit is taken off the top and reversed. Press it again and you get the one before that. The browser back button works identically over pages you visited. Neither could work as a queue, because a queue would hand you the oldest item first, meaning undo would reverse the very first thing you typed this morning. Most recent first is not a design preference here, it is the definition of what undo means.`,
`As a parser reads a JSON file, every opening brace or bracket is pushed onto a pile. Every closing one pops the top and checks that it matches. If it pops a curly brace when it sees a square bracket, the file is malformed and the parser knows exactly which position broke, which is how you get a precise error message instead of a vague one. If the pile is not empty when the file ends, something was opened and never closed. This is also what your editor uses to highlight the bracket matching the one under your cursor.`],

queue:[
`A user uploads a video and encoding it takes three minutes. If the web request did the encoding, the user would sit watching a spinner and the connection would probably time out. Instead the site writes a short message, encode video 123, onto a queue and immediately returns a page saying processing. Separate worker machines pull messages off that queue and do the actual work. The benefits compound: if the queue grows, you start more workers; if a worker crashes mid job, the message returns to the queue and another worker picks it up. Kafka, RabbitMQ and SQS are industrial versions of this idea.`,
`Your service can handle 100 requests per second. A marketing email goes out and traffic spikes to 500 per second for ten seconds. Without a queue, 400 requests per second get rejected outright and those users see errors. With a queue, the extra requests wait in line and get drained over the following forty seconds. Everyone is served, just some of them a little late. The queue also becomes your best warning signal: if its depth keeps climbing instead of draining, you are not handling a burst, you are permanently under capacity.`,
`A web server does not create a fresh thread for every request. Threads cost memory and switching between thousands of them wastes more time than it saves, so a traffic spike would take the server down. Instead the server starts a fixed pool, perhaps fifty threads, and puts arriving requests into a shared queue. Whenever a thread finishes a request it takes the next one from the queue. The pool size becomes a deliberate limit on how much work happens at once, and the queue holds everything waiting for a turn.`],

hashmap:[
`Rendering a profile page requires a database query that takes forty milliseconds. Since the same profile is requested constantly, you store the finished result in Redis under the key user:123. The next request hashes that key, jumps straight to the right bucket, and returns in under a millisecond with no database involved. The crucial property is that this stays fast whether the cache holds a hundred entries or fifty million, because hashing a key does not get slower as the store grows. That is the entire reason caches are built on hash maps rather than lists.`,
`You want the number of unique visitors today from a log of ten million page views. For each visitor id, check whether it is already in a hash set and add it if not. Each check is one lookup that does not care how many ids you already have. At the end, the size of the set is your answer. The naive version scans a list for each new id, which means ten million scans over a list that grows toward ten million entries, and that is comfortably in the trillions of comparisons. Same task, two very different outcomes.`,
`To join orders to customers when neither side is sorted, build a hash map from the smaller table first, mapping customer id to customer. Then walk the orders once and look up each customer id directly. One pass over each table, no sorting. Load balancers use the same mechanism for a different purpose: hash the session id and use the result to pick a server, which means the same user consistently lands on the same server and any data cached there stays useful.`],

'bst-insert':[
`Compare Java's HashMap with its TreeMap, or a Python dict with a sorted container. Both store keys and values and both let you look things up. But loop over a HashMap and the keys come out in a jumbled order that is not insertion order and not sorted order. Loop over a TreeMap and they come out sorted, because iterating one is an in-order walk of a balanced tree. If you have ever had a bug that only appears in some runs because code quietly depended on the order a map handed things back, this difference is usually the cause.`,
`A database index is a B-tree, which follows the same ordering rule as the tree you just watched but with one change: each node holds hundreds of keys instead of one. The reason is that disks and SSDs read in fixed blocks, so a read costs the same whether you use one key from it or five hundred. A two-way branch wastes almost the whole block. With a wide node, finding one row among ten million takes about three or four reads. The shape of the data structure is dictated by the cost of the hardware underneath it.`,
`Consider show me orders from the last hour, or players ranked 50th to 100th. With a hash map you would have to examine every single entry and test whether it falls in the range, because hashing deliberately destroys any relationship between nearby keys. With an ordered structure you jump to the start of the range and walk forward until you leave it, touching only the entries you are actually going to return. This is why Redis, which is otherwise a key-value store, ships a separate sorted set type specifically for leaderboards and time ranges.`],

'tree-pre':[
`You are saving a nested comment thread, or a folder structure, to a file so it can be restored later. Write the parent first, then its children. A reader rebuilding it works top down, and by the time any child appears in the file its parent already exists and is ready to attach to. If you wrote children first, the reader would be holding pieces with nothing to attach them to and would have to buffer everything until the end. The order you write in decides how simple the reader can be.`,
`Duplicating a nested structure, such as copying a document template with sections and subsections, follows the same shape. You create the top-level copy first, then create each child copy and attach it to the parent you just made. The copy grows downward in exactly the order the walk visits. Trying to do it in another order means creating orphaned pieces and stitching them together afterwards, which is more code and more chances to get it wrong.`,
`A web page is a tree: the page contains a sidebar, which contains a list, which contains items. The browser processes the container first because children are positioned and sized relative to it, so the parent's dimensions have to be known before any child can be placed. Any code that walks a component tree to render, measure or apply styles is doing a pre-order traversal, whether or not anyone calls it that.`],

'tree-in':[
`A query ends with ORDER BY created_at. If an index already keeps rows ordered by that column, the database does not sort anything at all. It walks the index in order and streams rows out as it goes. Sorting a million rows costs real time and often temporary disk space; walking a structure that is already ordered costs almost nothing. This is the concrete reason behind the common advice to add an index that matches the column you sort by, and why a query plan showing a sort step is often a sign something is missing.`,
`For a filter like age between 30 and 40, the database jumps to the first entry that is 30, walks forward in order, and stops at the first value past 40. If 5,000 rows out of 5 million match, it touches 5,000. Without the ordering it would have to examine all 5 million and test each one. The saving is not a constant factor, it scales with how selective your filter is, which is why range queries on indexed columns are fast and the same query on an unindexed column is not.`,
`A common and nasty bug is code that inserts a value on the wrong side of a node. The tree still looks fine and nothing crashes, but searches start missing values that are definitely in there, because the search takes a branch based on a rule the tree no longer obeys. The check is to walk the tree in order and print the values. If the output is not strictly ascending, the rule is broken, and the exact point where the sequence dips tells you where to look.`],

'tree-post':[
`In languages like C, memory is not cleaned up for you, so deleting a tree means freeing every node yourself. If you free the parent first, you have just destroyed the only record of where its children live. Those child nodes still occupy memory, but nothing in the program can reach them ever again, and the memory is lost until the process exits. That is a memory leak. Freeing children first and the parent last means every node is reachable at the moment you release it, and nothing is stranded.`,
`The du command reports how much space each folder uses. A folder's size is the sum of everything inside it, so the total for the top folder cannot be known until every subfolder has been finished. That is why running it on a large directory appears to hang and then print results from the deepest level upward. Any rolled-up total behaves this way: department costs built from team costs, or a query planner estimating the cost of an operation from the cost of its inputs.`,
`The expression 2 + 3 * 4 becomes a tree with the multiply node sitting above 3 and 4, and the plus node above 2 and the multiply. To compute the plus you need both numbers below it, so the multiply has to finish first. Write out the visit order and you get 2 3 4 * +, which is reverse Polish notation. Old HP calculators used this notation directly, and stack-based virtual machines still execute instructions in this order because each operator can simply take its operands off the top of the stack.`],

bfs:[
`Think of a puzzle where every move costs the same: sliding tiles into place, moving through a maze one square at a time, or a knight hopping around a chessboard. Breadth-first search explores every position reachable in one move, then every position reachable in two, then three. The first time it touches the goal, it has arrived in the fewest possible moves, because any shorter route would have shown up in an earlier round. The guarantee comes free from the order of exploration, with no extra bookkeeping.`,
`A crawler starting from a homepage has to choose what to follow next. Going depth-first risks diving into a date-based archive and spending hours twelve links deep in old posts before ever visiting the About page. Breadth-first visits everything the homepage links to, then everything those pages link to. The pages closest to the entry point, which are usually the important ones, come first, and you can stop at any depth and still have sensible coverage.`,
`Service A calls B and C, and B calls D. Service A goes down. Who is affected, and how badly? Walk outward from A one hop at a time: direct dependents first, then their dependents. The distance from A tells you how indirect the impact is, which helps you decide what to alert on and what can wait. The identical walk answers a different operational question, which caches need invalidating when a record changes, because that also spreads outward through references.`],

dfs:[
`Module A imports B, and B imports C. C has to be compiled first, then B, then A. Depth-first search dives all the way to the deepest dependency, finishes it, and works back up, so each module is completed only after everything it needs is done. Arranging the finish order gives you a valid build order, which is called a topological sort. Every build tool, bundler and package manager runs some version of this to decide what happens first, and it is why changing one low-level file can trigger a large rebuild.`,
`Now suppose A imports B, B imports C, and C imports A. There is no valid order, because each one needs another to go first. The detection is a small addition to the walk: mark each node as you enter it and unmark it when you leave. If you ever reach a node that is still marked, you have walked in a circle and the current path is the cycle. This is the circular dependency warning your bundler prints, and the same check is how systems detect deadlocks where two processes each hold what the other is waiting for.`,
`A garbage collector needs to know which objects your program can still reach. It starts from the roots, meaning the variables currently in scope, and follows every reference it finds, marking each object as it goes. When it has nowhere left to go, anything unmarked is unreachable by definition and its memory can be reclaimed. That marking phase is a depth-first traversal of the object graph. Walking a directory tree recursively is the same algorithm over a friendlier graph.`],

dijkstra:[
`Roads carry costs that have nothing to do with how many of them you take. Five kilometres of motorway might be three minutes, while one kilometre through the city centre is four. So the route with the fewest turns is frequently not the fastest. Dijkstra repeatedly expands whichever partial route is cheapest so far, which means the first time it reaches your destination, that total is the lowest achievable. Real map engines add heavy optimisations because running this across an entire country for every request would be far too slow, but this is the core they are optimising.`,
`Routers inside a company network share a map of which links exist and what each one costs, with cost derived from bandwidth. Each router runs Dijkstra over that shared map to work out the best next hop for every destination, and stores the results in its forwarding table. When a cable is cut, the map changes and every router recomputes within seconds, which is how traffic reroutes without anyone intervening. Without this, a router would only know about its immediate neighbours and would have no basis for choosing between them.`,
`Moving data between cloud regions, where each hop has a price per gigabyte and a latency. Choosing a path through a content delivery network. Picking a sequence of currency conversions with a fee at each step. In all of these your options form a network and every step carries a number, so the same algorithm applies unchanged and only the meaning of the number differs. Recognising that a problem is really a weighted graph is usually the hard part; once you see it, the algorithm is already written.`]
};
export { USE_DETAIL };
